name: ci-code-quality
description:
  Run code quality checks including linting, vulnerability scanning, and tests
  with coverage checks.
author: aditor@gmail.com

branding:
  icon: eye
  color: red

inputs:
  runLint:
    description: 'Run ESLint'
    default: 'true'

  runAudit:
    description: 'Run npm audit'
    default: 'true'

  runUnitTests:
    description: 'Run tests'
    default: 'true'

  unitTestCommand:
    description: 'Test command to run'
    default: 'npm run test:unit -- --coverage'

  minCoverage:
    description: 'Minimum test coverage threshold (%)'
    default: '65'

  relativePath:
    description: 'Relative path to the project directory'
    default: '.'

  reportTitle:
    description: 'Title for the report'
    default: 'Code Quality Report'

outputs:
  report:
    description: Code Quality Report
  coverage:
    description: Test Coverage Percentage

runs:
  using: node20
  main: dist/index.js
