name: ci-code-quality
description:
  Run code quality checks including linting, vulnerability scanning, and tests
  with coverage checks.
author: aditor@gmail.com

branding:
  icon: eye
  color: red

inputs:
  runLint:
    description: 'Run ESLint'
    default: 'true'
    required: false

  runAudit:
    description: 'Run npm audit'
    default: 'true'
    required: false

  runTests:
    description: 'Run tests'
    default: 'true'
    required: false

  testCommand:
    description: 'Test command to run'
    default: 'npm run test:unit -- --coverage'
    required: false

  minCoverage:
    description: 'Minimum test coverage threshold (%)'
    default: '65'
    required: false

  relativePath:
    description: 'Relative path to the project directory'
    default: '.'
    required: false

outputs:
  report:
    description: Code Quality Report
  coverage:
    description: Test Coverage Percentage

runs:
  using: node20
  main: dist/index.js
